### PR TITLE
Fix #4 and #5.

### LINKED ISSUE #4: Update the logo.
Let's update the logo.

### PR DESCRIPTION
**Pull request by jbucaran**
Let's squash all these commits into a single commit. 🙏

### CODE REVIEW

**Comment by jbucaran** [comment]
Whoops. I thought I done that. Let me fix that.

**Comment by jbucaran** [comment]
@tobiasbueschel I don't know how to fix this. See:

screen shot 2017-06-13 at 0 33 23

Any clue? I use macOS.

**Comment by tobiasbueschel** [comment]
@jbucaran have you tried: https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git?

**Comment by lukejacksonn** [comment]
`git mv -f LICENCE.md licence.md` sounds about right

**Comment by jbucaran** [comment]
Thank you both! I did it all by myself! 💪

**Pull request merged**
