### PR TITLE
add hyperapp-transitions

### PR DESCRIPTION
**Pull request by zaceno**
Since it's not an "app/boilerplate", and all the bullets under "resources" were docs/forums, I added a new heading I called "add-ons"

### CODE REVIEW

**Comment by jbucaran** [comment]
add-ons? Nice. 👍

**Comment by zaceno** [comment]
@jbucaran Yeah, not sure if that's the best heading, but I think it conveys the idea. Helpers/Libraries/Mixins/whatevers that enhance or work with HyperApp. Maybe "libraries", or perhaps "libraries & mixins" (although mine is not a mixin)

**Comment by jbucaran** [comment]
@zaceno "libraries & mixins" maybe better, though, since we never use the word add-on anywhere. What do you think?

**Comment by zaceno** [comment]
@jbucaran yes, that sounds better! I'll fix the PR

**Comment by zaceno** [comment]
@jbucaran Fixed it! (not sure you'd be notified by just me adding a commit)

**Comment by zaceno** [comment]
@tobiasbueschel Great nitpick! No need to apologize :) I updated the description according to your suggestion.

**Comment by tobiasbueschel** [comment]
ace @zaceno 💯

**Pull request merged**
