### PR TITLE
add Simplified Chinese hyperapp.js.cool

### PR DESCRIPTION
**Pull request by willin**

### CODE REVIEW

**Comment by jorgebucaran** [comment]
@willin Looks awesome, did you make all that?

One pet peeve: Find & replace all instances of `HyperApp` → `Hyperapp`. 🙏

**Comment by willin** [comment]
sure

**Comment by willin** [comment]
done https://github.com/willin/hyperapp.js.cool/commit/6b9ba9d1bc5f9497eb0047c8ac5d49948c622414

**Comment by jorgebucaran** [comment]
Thanks, @willin! 🎉

**Comment by jorgebucaran** [comment]
@willin You forgot one: 从0到1掌握HyperApp. 😄

**Pull request merged**
