### PR TITLE
Add https://github.com/spapas/hyperapp-tutorial

### PR DESCRIPTION
**Pull request by spapas**
Add my hyperapp tutorial application to "Examples".

### CODE REVIEW

**Comment by jorgebucaran** [comment]
Could we come up with a more original name than "A Hyperapp Tutorial"? 😄 

@zaceno

**Comment by spapas** [comment]
What about Serafeim's hyperapp tutorial ?

**Comment by jorgebucaran** [comment]
"Serafeim's Hyperapp Tutorial" sounds great! 💯

**Comment by spapas** [comment]
Thanks !

**Comment by jorgebucaran** [comment]
Thank you! 🎉

**Pull request merged**
