### PR TITLE
added link for hyperapp-responsive-admin

### PR DESCRIPTION
**Pull request by jdh2550**
A simple example / boilerplate for working with a login form and with GraphQL

### CODE REVIEW

**Comment by jorgebucaran** [comment]
Thanks, @jdh2550. Looks nice! Could you improve the README appearance a bit more? Use proper capitalization, etc. Maybe you can get some ideas from this [template](https://gist.github.com/JorgeBucaran/533f75c2330cf79afc2e622ad7a07e84).

**Comment by jdh2550** [comment]
Ha, I used lowercase for headings following the style of the boilerplate I started with :-)

But I'm happy to change it - is the new readme a bit nicer?

**Comment by jorgebucaran** [comment]
Thanks, @jdh2550!

**Comment by jdh2550** [comment]
I'm a recent hyperapp convert (from react/redux) - and I'm happy to add my small part to the community.  I love hyperapp.

**Comment by jorgebucaran** [comment]
Awesome to hear that. Welcome aboard!!

**Pull request merged**
